#服务端设置
server:
  port: 80
  #ip,域名都设置在address
  address: 10.41.2.10
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://10.41.0.14:3306/testzabbix?characterEncoding=utf8&useSSL=false
    username: test
    password: 123456

#日志设置
logging:
  #日志文件,绝对路径或相对路径（可以设置文件名称）
  file: /tmp/ragdollhouselog/log.log
  #file: D:/360Downloads/log.log
  level:
    club:
      ragdollhouse:
        #数据库操作打印日志
        Mapper: debug
    org:
      springframework:
        web: debug

#HTTP编码设置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true